### ISSUE TITLE
Investigate flask API responding to TCP request and returning JSON without saving internally

### ISSUE THREAD

**Issue by samer-12** [gintel-as/gsp24-sipviewer#185]
Like discussed with Bjørn, would be ideal if we never write files to the python server.
Could be solved by passing the JSONtext from LogInterpreter to the API, and sending this as a response, either as simply a json object or converted into a file first.

**Comment by moltubaer** [comment]
If not able to, then you should at least add a function that deletes the processed log file after it has been downloaded
